### ISSUE TITLE
Find Stanford NLP Docker image

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/MathQA#5]
This will reduce the build time for the VM.
@vstange do you have an idea?

https://github.com/ag-gipp/MathQA/blob/07adb873dcc99a473198a89faf075a979cd2e6b9/Dockerfile#L8-L13

**Comment by vstange** [comment]
Plenty of ideas:
1. It seems the stanford library could be put in its own image.
2. The order should definitely changed! Always start with things that don't change - this way you can utilize the local docker cache for intermediate images. E.g. first load stanford, then copy only the requirements and after that you can copy the rest of the code. The code is most likely to change every time - so this comes last.
3. @physikerwelt should this image run 2 processes? the stanford server and the pyhton application? If so, the run commands should be executed in a single CMD line. Otherwise we could use supervisor.

**Comment by physikerwelt** [comment]
I think we should have two containers. The container creation takes too long at this moment. I was hoping for a premade NLP container...
